sonar.projectKey=ford-phatchara_backend-go
sonar.organization=ford-phatchara
sonar.projectName=Backend-GO
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/vendor/**,**/tmp/**,**/bin/**,**/coverage/**
sonar.login=1a4b0459f8b394c66d8a245d269790060f401e58
sonar.host.url=https://sonarcloud.io
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out