sonar.projectKey=ford-phatchara_backend-go
sonar.projectName=Backend-GO
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/vendor/**,**/tmp/**,**/bin/**,**/coverage/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
