import { MaintenanceLog } from '../models/maintenance-log.model';
import { Plot } from '../models/plot.model';
import { Sale } from '../models/sale.model';

export const MOCK_PLOTS: Plot[] = [
  {
    id: 'plot-north-01',
    name: 'North Ridge',
    size: 4.2,
    notes: 'Older Monthong trees with strong morning sun and drip irrigation.',
  },
  {
    id: 'plot-east-02',
    name: 'East Canal',
    size: 3.1,
    notes: 'Good drainage, mixed Chanee and Monthong, needs weekly mulch checks.',
  },
  {
    id: 'plot-south-03',
    name: 'South Orchard',
    size: 5.4,
    notes: 'Highest yield block, shade cloth along the western edge.',
  },
  {
    id: 'plot-nursery-04',
    name: 'Nursery Rows',
    size: 1.6,
    notes: 'Young replacement trees and grafting trial rows.',
  },
];

export const MOCK_SALES: Sale[] = [
  {
    id: 'sale-001',
    date: '2026-01-12',
    plot: 'North Ridge',
    grade: 'A',
    weightKg: 320,
    pricePerKg: 145,
    totalPrice: 46400,
  },
  {
    id: 'sale-002',
    date: '2026-01-28',
    plot: 'East Canal',
    grade: 'B',
    weightKg: 180,
    pricePerKg: 98,
    totalPrice: 17640,
  },
  {
    id: 'sale-003',
    date: '2026-02-10',
    plot: 'South Orchard',
    grade: 'A',
    weightKg: 410,
    pricePerKg: 152,
    totalPrice: 62320,
  },
  {
    id: 'sale-004',
    date: '2026-02-24',
    plot: 'North Ridge',
    grade: 'B',
    weightKg: 210,
    pricePerKg: 102,
    totalPrice: 21420,
  },
  {
    id: 'sale-005',
    date: '2026-03-08',
    plot: 'South Orchard',
    grade: 'A',
    weightKg: 385,
    pricePerKg: 158,
    totalPrice: 60830,
  },
  {
    id: 'sale-006',
    date: '2026-03-19',
    plot: 'East Canal',
    grade: 'A',
    weightKg: 275,
    pricePerKg: 149,
    totalPrice: 40975,
  },
  {
    id: 'sale-007',
    date: '2026-04-03',
    plot: 'North Ridge',
    grade: 'A',
    weightKg: 360,
    pricePerKg: 162,
    totalPrice: 58320,
  },
  {
    id: 'sale-008',
    date: '2026-04-16',
    plot: 'South Orchard',
    grade: 'B',
    weightKg: 240,
    pricePerKg: 110,
    totalPrice: 26400,
  },
];

export const MOCK_MAINTENANCE_LOGS: MaintenanceLog[] = [
  {
    id: 'care-001',
    date: '2026-01-05',
    plot: 'North Ridge',
    wateringMinutes: 90,
    fertilizing: true,
    notes: 'Applied compost tea after a dry week.',
  },
  {
    id: 'care-002',
    date: '2026-01-18',
    plot: 'East Canal',
    wateringMinutes: 75,
    fertilizing: false,
    notes: 'Cleared fallen leaves from irrigation line.',
  },
  {
    id: 'care-003',
    date: '2026-02-04',
    plot: 'South Orchard',
    wateringMinutes: 110,
    fertilizing: true,
    notes: 'Potassium blend before fruit sizing period.',
  },
  {
    id: 'care-004',
    date: '2026-02-19',
    plot: 'Nursery Rows',
    wateringMinutes: 45,
    fertilizing: false,
    notes: 'Checked graft ties and replaced two stakes.',
  },
  {
    id: 'care-005',
    date: '2026-03-07',
    plot: 'East Canal',
    wateringMinutes: 80,
    fertilizing: true,
    notes: 'Mulch refreshed around young Chanee trees.',
  },
  {
    id: 'care-006',
    date: '2026-03-22',
    plot: 'North Ridge',
    wateringMinutes: 95,
    fertilizing: false,
    notes: 'Pruned low branches and checked moisture sensors.',
  },
  {
    id: 'care-007',
    date: '2026-04-06',
    plot: 'South Orchard',
    wateringMinutes: 120,
    fertilizing: true,
    notes: 'Foliar feed after harvest pass.',
  },
  {
    id: 'care-008',
    date: '2026-04-18',
    plot: 'Nursery Rows',
    wateringMinutes: 50,
    fertilizing: true,
    notes: 'Light organic fertilizer and pest inspection.',
  },
  {
    id: 'care-009',
    date: '2026-04-22',
    plot: 'East Canal',
    wateringMinutes: 85,
    fertilizing: false,
    notes: 'Irrigation cycle and canal bank inspection.',
  },
];
