sonar.projectKey=project-ai-frontend-next
sonar.projectName=Frontend-NextJS
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
