sonar.projectKey=project-ai-frontend-next
# sonar.organization=ford-phatchara
sonar.projectName=Frontend-NextJS
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.login=1a4b0459f8b394c66d8a245d269790060f401e58
# sonar.host.url=https://sonarcloud.io